CREATE TABLE deck (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE card (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  front_name VARCHAR(255) NOT NULL,
  back_name VARCHAR(255) NOT NULL,
  deck_id INTEGER NOT NULL
);

ALTER TABLE card ADD CONSTRAINT fk_deck_id FOREIGN KEY (deck_id) REFERENCES deck (id);