CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE decks (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL
);

CREATE TABLE cards (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  front_name VARCHAR(255) NOT NULL,
  back_name VARCHAR(255) NOT NULL,
  deck_id INTEGER NOT NULL
);

ALTER TABLE decks ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE cards ADD CONSTRAINT fk_deck_id FOREIGN KEY (deck_id) REFERENCES decks (id);